export const APP_STATUS = {
    UNLOAD: 'UNLOAD',
    LOADING: 'LOADING',
    LOADED: 'LOADED',
    LOAD_ERR: 'LOAD_ERR',

    BOOTSTRAPPING: 'BOOTSTRAPPING',
    BOOTSTRAPPED: 'BOOTSTRAPPED',

    MOUNTING: 'MOUNTING',
    MOUNTED: 'MOUNTED',

    UNMOUNTING: 'UNMOUNTING',
    UNMOUNT: 'UNMOUNT',

}

export const FIRST_APP_MOUNT = 'FIRST_APP_MOUNT'

export const IFRAME_SRC = '/api.json'
